// @ts-check
// Locked information architecture — see the plan file.
// Slugs are brand-neutral: no "mcp-for-unity" / "unity-mcp" in any URL.
// Pages flagged TODO land in later milestones (M3 generator, M4 net-new).
// Keep the structure stable to avoid URL breakage.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/index' },
      collapsed: false,
      items: [
        'getting-started/install',
        'getting-started/first-prompt',
        'getting-started/clients',
        'getting-started/migrate',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/uv-setup',
        'guides/claude-code-cli',
        'guides/client-configurators',
        'guides/multi-instance',
        'guides/tool-groups',
        'guides/cli',
        'guides/cli-examples',
        'guides/custom-tools',
        'guides/remote-server-auth',
        'guides/security',
        'guides/roslyn',
        'guides/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Tools',
          // Tools IS the catalog — clicking it navigates to the index.
          // Each group subdir under reference/tools/ ships its own
          // `_category_.json` (emitted by tools/generate_docs_reference.py)
          // so the autogenerated walk wraps each as a collapsible group.
          // Parent's `link:` causes Docusaurus to exclude reference/tools/index
          // from the autogenerated children — so no duplicate "Tools" entry.
          link: { type: 'doc', id: 'reference/tools/index' },
          items: [{ type: 'autogenerated', dirName: 'reference/tools' }],
        },
        {
          type: 'doc',
          id: 'reference/resources/index',
          label: 'Resources',
        },
        'reference/cli',
        'reference/manifest',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'architecture/transports',
        'architecture/instance-routing',
        'architecture/python-layers',
        'architecture/unity-compat',
        'architecture/remote-auth',
        'architecture/telemetry',
        'architecture/manage-physics',
        'architecture/project-roadmap',
        'architecture/roadmap',
        'architecture/external-analytics',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        'contributing/dev-setup',
        'contributing/testing',
        'contributing/releases',
        'contributing/docs',
      ],
    },
    {
      type: 'category',
      label: 'Migrations',
      collapsed: true,
      items: [
        'migrations/v5',
        'migrations/v6',
        'migrations/v8',
        'migrations/v10',
      ],
    },
    'releases',
  ],
};

export default sidebars;
